import { apiFetch } from './client';
import { Paciente, Turno } from './types';

interface TurnoDto {
  Codigo: number;
  Fecha: string;
  Hora: string;
  Prestador: string;
  Mutual: string | null;
  Autogestion: boolean;
  PideCodigoSeguridad: boolean;
}

interface AtencionResponseDto {
  Tipo: 'turnos' | 'derivado';
  Paciente: { Codigo: number; Dni: string; NombreYApellido: string; Mutual: string | null } | null;
  Turnos: TurnoDto[] | null;
}

export type ResultadoAtencion =
  | { tipo: 'turnos'; paciente: Paciente; turnos: Turno[] }
  | { tipo: 'derivado'; paciente?: Paciente };

export async function buscarAtencion(sucursalId: number, dni: string): Promise<ResultadoAtencion> {
  const query = new URLSearchParams({ sucursal: String(sucursalId), dni });
  const data = await apiFetch<AtencionResponseDto>(`/api/atencion?${query}`);

  const paciente: Paciente | undefined = data.Paciente
    ? {
        codigo: data.Paciente.Codigo,
        dni: data.Paciente.Dni,
        nombreYApellido: data.Paciente.NombreYApellido,
        mutual: data.Paciente.Mutual ?? '',
      }
    : undefined;

  if (data.Tipo === 'turnos' && paciente && data.Turnos && data.Turnos.length > 0) {
    return {
      tipo: 'turnos',
      paciente,
      turnos: data.Turnos.map((t) => ({
        codigo: t.Codigo,
        fecha: t.Fecha,
        hora: t.Hora,
        prestador: t.Prestador,
        mutual: t.Mutual ?? '',
        autogestion: t.Autogestion,
        pideCodigoSeguridad: t.PideCodigoSeguridad,
      })),
    };
  }

  return { tipo: 'derivado', paciente };
}

export async function confirmarTurno(sucursalId: number, dni: string, turnoCodigo: number): Promise<void> {
  await apiFetch('/api/atencion/confirmar', {
    method: 'POST',
    body: { Sucursal: sucursalId, Dni: dni, TurnoCodigo: turnoCodigo },
  });
}

/**
 * Registers the patient in the Recepcion queue and returns the llamado number generated by the backend.
 * `pacienteCodigo` is null when the DNI does not match any paciente.
 */
export async function insertarLlamado(sucursalId: number, dni: string, pacienteCodigo: number | null): Promise<number> {
  const data = await apiFetch<{ Numero: number }>('/api/atencion/llamado', {
    method: 'POST',
    body: { Sucursal: sucursalId, Dni: dni, PacienteCodigo: pacienteCodigo },
  });
  return data.Numero;
}
